### ISSUE TITLE
Test pagination

### ISSUE THREAD

**Issue by flodlc** [PolytechLyon/cloud-project-equipe-3-2#3]
Est-ce qu'il y a pas un problème sur ce slide : [https://slashgear.github.io/cloud/#/5](url) ?
Dans les tests de pagination, il faut que le résultat de la page 0 soit différent que celui de la page 1.
Mais que get/user sans paramètre retourne la page 0. 
Du coup la page par défaut devrait pas plutôt être 0 ?

**Comment by Slashgear** [comment]
Bien vu je corrige ça

**Comment by flodlc** [comment]
ok, merci !
